fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.20.0
    python:
      repo: https://github.com/stankevich/puppet-python.git
      ref: 2.4.2
  symlinks:
    thumbor: "#{source_dir}"

