---
sudo: false
dist: trusty
language: ruby
cache: bundler
bundler_args: --without system_tests
script: 'bSPEC_OPTS="--format documentation" bundle exec rake validate lint spec'
#Inserting below due to the following issue: https://github.com/travis-ci/travis-ci/issues/3531#issuecomment-88311203
before_install:
  - rm Gemfile.lock || true
  - gem update bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0" PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0" PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-9
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.4.0
    env: PUPPET_GEM_VERSION="~> 5.0" PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.4.0
    env: PUPPET_GEM_VERSION="~> 5.0" PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-9
    script: bundle exec rake beaker
    services: docker
    sudo: required
notifications:
  email: false

